[package]
name = "ntp_proxy"
version = "0.1.0"
authors = ["Finn Behrens <fin@nyantec.com>"]
edition = "2018"
license = "MirOS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28"
afpacket = "0.1.5"
anyhow = "1.0.42"